version: '2'

networks:
    laravelsite:

services: 

     # The Application
    app:
        build: 
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        environment: 
            - "DB_PORT=3306"
            - "DB_HOST=database"
        networks: 
            - laravelsite

    # The Web Server
    web:
        build: 
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - 8000:80
        networks:
            - laravelsite
    
    # The Database
    database:
        image: mysql:5.6
        volumes: 
            - dbdata:/var/lib/mysql
        environment: 
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=laravel"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports: 
            - "33061:3306"
        networks: 
            - laravelsite
    
    # phpMyAdmin
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravelsite

volumes:
    dbdata: